version: '3.7'
services:
  effectapp-db:
    container_name: effectapp-db
    image: mysql:8.0
    networks:
      - effectapp-network
    environment:
      - MYSQL_DATABASE=effectapp
      - MYSQL_ROOT_PASSWORD=Hoppenhof.20
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Hoppenhof.20
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  signify-backend:
    build:
      context: .
    container_name: signify-backend
    image: jordywalraven/signify-backend:latest
    ports:
      - "8080:8080"
    networks:
      - effectapp-network
    depends_on:
      - effectapp-db
    environment:
      - DB_SERVER=jdbc:mysql://effectapp-db/effectapp?useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_HOST=effectapp-db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Hoppenhof.20
      - MYSQL_DATABASE=effectapp
      - MYSQL_PORT=3306

networks:
  effectapp-network:
    name: effectapp-network

volumes:
  dbvol:
